# SPDX-FileCopyrightText: 2021, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

[package]
edition = "2018"
name = "spdx-to-dep5"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10.0"
async-stream = "0.3.2"
chrono = {version = "0.4.19", features = ["serde"]}
derive_more = "0.99"
futures = "0.3.17"
indextree = "4.4"
itertools = "0.10"
lazy_static = "1.4"
regex = "1.5"
serde = "1.0"
spdx-rs = "0.3.0"
thiserror = "1.0"
typed-index-collections = "3.0"

[dependencies.key-value-parser]
git = "https://github.com/rpavlik/key-value-parser-rs"
rev = "0.1.0"
