# SPDX-FileCopyrightText: 2021-2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

[package]
edition = "2018"
name = "spdx-to-dep5"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
indextree = "4.4"
itertools = "0.10"
lazy_static = "1.4"
regex = "1.5"
spdx-rs = "0.5.0"
thiserror = "1.0"
typed-index-collections = "3.0"
log = "0.4"
env_logger = "0.9"
