# SPDX-FileCopyrightText: 2021, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

[package]
edition = "2018"
name = "spdx-to-dep5"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10.0"
async-stream = "0.3.2"
chrono = {version = "0.4.19", features = ["serde"]}
futures = "0.3.17"
regex = "1.5.4"
serde = "1.0.130"
spdx-rs = {path = "../spdx-rs/"}
thiserror = "1.0.30"

[dependencies.key-value-parser]
git = "https://github.com/rpavlik/key-value-parser-rs"
rev = "0.1.0"
